name: master-CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:

  build:
    permissions:
      contents: write
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Pack ipk
        uses: resmh/action-ipkpack@master
        with:
          timestamp: 1
          timestamp_path: 1
          
      - name: Create single package repository
        uses: resmh/action-ipkrepo@main
        with:
          privategpg: ${{ secrets.GPGREPOKEY }}
          privatesignify: ${{ secrets.SIGNIFYREPOKEY }}
      
      - name: Release ipk and index
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Automated Release"
          files: |
            ddns-scripts-ionos.ipk
            Packages
            Packages.asc
            Packages.sig
            ddns_scripts_ionos.gpg.pub
            ddns_scripts_ionos.signify.pub
